transcriber_config:
  backend_root: https://cashee.ru:447/api
  user: support
  password: 8364Veakjybot@69$1

vad_model_path: vad_models/vad/model.ckpt-200106
#aggression_cnn_model_path: aggr_models/agression_cnn_model.h5
aggression_cnn_model_path: aggr_models/20191017_my_weights_v1.h5
aggression_activation_threshold: 0.67