# ==================================================================
# module list
# ------------------------------------------------------------------
# ffmpeg libsndfile1 sox libsox-fmt-all              	(apt)
# librosa pyyaml pika requests pydub              	(pip)
# ==================================================================

FROM tensorflow/tensorflow:latest-gpu-py3-jupyter

RUN apt install -y  libsndfile1
RUN pip install pandas librosa tqdm keras seaborn

RUN mkdir /root/app
COPY . /root/app

ENTRYPOINT ["jupyter", "notebook", "--notebook-dir", "/home/gpn", "--ip=0.0.0.0", "--allow-root"]